name: came
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  image: ^3.0.1
  get: ^4.6.6
  google_ml_kit: ^0.19.0
  tflite_flutter: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/ssd_mobilenet.tflite
    - assets/model.tflite
    - assets/labels.txt
